version: '3.8'
services:
  analysis:
    #build: 
    #  dockerfile: .docker/Dockerfile
    #  context: .
    container_name: lcolling/odp-geniole
    image: lcolling/odp-geniole
    volumes:
      - .:/home/rstudio
    environment:
      DISABLE_AUTH: 'true'
    working_dir: /home/rstudio
    command: make analysis-docker
  download:
    container_name: lcolling/odphelper:download
    image: lcolling/odphelper:download
    volumes:
      - .:/home/rstudio
    environment:
      DISABLE_AUTH: 'true'
    working_dir: /home/rstudio
    command: make download-docker
  document:
    container_name: lcolling/odphelper:knit
    image: lcolling/odphelper:knit
    volumes:
      - .:/home/rstudio
    environment:
      DISABLE_AUTH: 'true'
    working_dir: /home/rstudio
    command: make document-docker
