# This is a basic workflow to help you get started with Actions

name: autobuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: building
      run: |
        make all
        echo "<a href=\"$(basename `ls docs/*.pdf`)\">Document</a>" > index.html  
        

    # Runs a set of commands using the runners shell
    - uses: EndBug/add-and-commit@v4
      with:
        add: docs/*.pdf index.html
        author_name: Lincoln Colling
        author_email: lincoln@colling.net.nz
        message: "built from github action"   
        ref: gh-pages
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
